image: srcoder/development-php:php71-fpm
definitions:
  caches:
    vendor: vendor
pipelines:
  default:
    - step:
        name: Composer validation
        script:
          - composer show --platform
          - composer validate --strict --no-interaction

    - step:
        name: Testing suite
        caches:
          - composer
          - vendor
        script:
          - composer self-update
          - composer config --global http-basic.composer.mediact.nl $COMPOSER_MEDIACT_NL_USER $COMPOSER_MEDIACT_NL_PASS
          - composer install --dev --prefer-dist --no-scripts --no-progress --optimize-autoloader --no-interaction -vvv
          - composer show
          - composer exec -v grumphp run
